name: API CI

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: npx nx run api:test:ci --skip-nx-cache

      - name: Build API
        run: npx nx run api:build --skip-nx-cache
