name: UI CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: yarn install

      - name: Build UI
        run: npx nx run ui:build:production --skip-nx-cache

      - name: Dockerize UI
        run: docker build -f apps/ui/Dockerfile . -t email_sweeperr_client

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push email_sweeperr_client
